language: bash
sudo: required
env:
  matrix:
  - DEPLOY_ENVIRONMENT=staging
services:
- docker
script:
- |
  if [ "${DEPLOY_ENVIRONMENT}" != "" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${TRAVIS_BRANCH}" == "master" ] &&\
     [ "${TRAVIS_COMMIT_MESSAGE}" != "" ] && ! echo "${TRAVIS_COMMIT_MESSAGE}" | grep -- --no-deploy && [ "${TRAVIS_COMMIT}" != "" ]
  then
      openssl aes-256-cbc -K $encrypted_694412885976_key -iv $encrypted_694412885976_iv -in k8s-ops-secret.json.enc -out secret-k8s-ops.json -d
      K8S_ENVIRONMENT_NAME="${DEPLOY_ENVIRONMENT}"
      IMAGE_TAG="gcr.io/uumpa123/sk8s-ops:${TRAVIS_COMMIT}"
      B64_UPDATE_VALUES=`echo '{"sk8s-ops":{"image":"'${IMAGE_TAG}'"}}' | base64 -w0`
      # wget https://raw.githubusercontent.com/OriHoch/sk8s-ops/master/run_docker_ops.sh
      chmod +x run_docker_ops.sh
      ./run_docker_ops.sh "${K8S_ENVIRONMENT_NAME}" "
           ! ./helm_update_values.sh '${B64_UPDATE_VALUES}' \
                                     '${K8S_ENVIRONMENT_NAME} ops image update --no-deploy' \
                                     '${K8S_OPS_GITHUB_REPO_TOKEN}' \
                                     'OriHoch/sk8s' \
                                     'master' \
              && echo 'failed helm update values' && exit 1
           ! kubectl set image deployment/ops ops=$IMAGE_TAG \
              && echo 'failed to patch deployment' && exit 1
           ! gcloud container builds submit --tag $IMAGE_TAG /app \
              && echo 'failed to build app image' && exit 1
           exit 0
      " "orihoch/sk8s-ops" "OriHoch/sk8s" "master" "" "-v `pwd`:/app"
  fi
