{{ if .Values.enabled }}{{ if .Values.image }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ops
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ops
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.global.defaultNodePool | quote }}
      containers:
      - name: ops
        image: {{ .Values.image | quote }}
        resources:
          requests:
            cpu: {{ .Values.cpuRequests | default "0.001" | quote }}
            memory: {{ .Values.memoryRequests | default "10Mi" | quote }}
          limits:
            {{ if .Values.cpuLimits }}cpu: {{ .Values.cpuLimits | quote }}{{ end }}
            {{ if .Values.memoryLimits }}memory: {{ .Values.memoryLimits | quote }}{{ end }}
        command:
        - bash
        - "-c"
        - "while true; do sleep 86400; done"
        {{ if .Values.secret }}
        volumeMounts:
        - name: k8s-ops
          mountPath: /k8s-ops
          readOnly: true
        {{ end }}
      {{ if .Values.secret }}
      volumes:
      - name: k8s-ops
        secret:
          secretName: {{ .Values.secret | quote }}
      {{ end }}
{{ end }}{{ end }}
