{{ if .Values.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ops
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ops
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.global.defaultNodePool | quote }}
      containers:
      - name: ops
        image: {{ .Values.image | default "orihoch/sk8s-ops@sha256:6c368f75207229c8bb2ccb99bd6414dfb21289c5c988d2381a9da2015f55bd38" | quote }}
        env:
        {{ if .Values.OPS_REPO_BRANCH }}
        - name: OPS_REPO_BRANCH
          value: {{ .Values.OPS_REPO_BRANCH | quote }}
        {{ end }}
        {{ if .Values.OPS_REPO_SLUG }}
        - name: OPS_REPO_SLUG
          value: {{ .Values.OPS_REPO_SLUG | quote }}
        {{ end }}
        resources:
          requests:
            cpu: {{ .Values.cpuRequests | default "0.001" | quote }}
            memory: {{ .Values.memoryRequests | default "10Mi" | quote }}
          limits:
            {{ if .Values.cpuLimits }}cpu: {{ .Values.cpuLimits | quote }}{{ end }}
            {{ if .Values.memoryLimits }}memory: {{ .Values.memoryLimits | quote }}{{ end }}
        command:
        - bash
        - "-c"
        - "while true; do sleep 86400; done"
        {{ if .Values.secret }}
        volumeMounts:
        - name: k8s-ops
          mountPath: /k8s-ops
          readOnly: true
        {{ end }}
      {{ if .Values.secret }}
      volumes:
      - name: k8s-ops
        secret:
          secretName: {{ .Values.secret | quote }}
      {{ end }}
{{ end }}
